pipeline {
    agent { dockerfile true }
    stages {
        stage('Build') {
            steps {
                sh 'docker --version'
                sh 'git --version'
            }
        }
    }
}
